npcs:
  "3": "Newbie Adviser"
  # bank npc
  "21": "Jack"
  # leader board npc
  "9": "Irisia"

items:
  steak: "COOKED_BEEF"
  cod: "COD"
  tutorialBook: "BOOK name:spawnTourBook lore:หนังสือสำหรับเดินเล่นรอบspawn  enchants:UNBREAKING:3+"
