npcs:
  "3": "Newbie Adviser"
  # bank npc
  "21": "Jack"
  # leader board npc
  "9": "Irisia"

items:
  steak: "COOKED_BEEF"
  cod: "COD"
  enchantment_book: "WRITTEN_BOOK title: Enchantments_Guide author: &eSage_of_Enchantments"
